### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by aliwebto** [lilendian0x00/xray-knife#1]
how to install and use in ubuntu ?

**Comment by lilendian0x00** [comment]
Download and extract it from this link:
`https://github.com/lilendian0x00/xray-knife/releases/download/v2.8.13/Xray-knife-linux-64.zip`

and then copy the binary to one of the directories specified in your Linux `$PATH` environment (e.g. `/usr/bin`). 

Restart your shell (`bash`) and run `xray-knife`
