### ISSUE TITLE
SSL/TLS Certificate Issue When Using Proxy Method

### ISSUE THREAD

**Issue by Mester-Dariush** [lilendian0x00/xray-knife#10]
Hello,

I am encountering an SSL/TLS certificate issue when using the proxy method. Below are the details of the commands I am using and the error I receive.

**Commands:**
To create the proxy:

`xray-knife proxy -v -p 2342  -c vless://..........`

To test the proxy:

`curl --proxy socks5://localhost:2342 https://api.ipify.org?format=json`

Error:
`curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed`

Terminal Output:

```
==========INBOUND==========
Protocol: Socks
Remark: Listener
Network: tcp
Address: 127.0.0.1
Port: 2342
============================

==========OUTBOUND==========
Protocol: Vless
Remark:
Network: tcp
Address: 80.253.255.10
Port: 443
UUID: 7c7af2de-bb97-429f-ac3c-8ef849717491
Flow: none
TLS: none
============================
2024/06/30 15:34:15 [Debug] app/log: Logger started
2024/06/30 15:34:15 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:2342
2024/06/30 15:34:15 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:2342
2024/06/30 15:34:15 [Info] transport/internet/udp: listening UDP on 127.0.0.1:2342
2024/06/30 15:34:15 [Warning] core: Xray 1.8.13 started
[+] 15:34:15 Started listening for new connections...
2024/06/30 15:34:29 [Info] [510997808] proxy/socks: TCP Connect request to tcp:104.26.13.205:443
2024/06/30 15:34:29 tcp:127.0.0.1:64690 accepted tcp:104.26.13.205:443 [socks >> proxy]
2024/06/30 15:34:34 [Info] [510997808] app/dispatcher: default route for tcp:104.26.13.205:443
2024/06/30 15:34:34 [Info] [510997808] transport/internet/tcp: dialing TCP to tcp:80.253.255.10:443
2024/06/30 15:34:34 [Debug] transport/internet: dialing to tcp:80.253.255.10:443
2024/06/30 15:34:34 [Info] [510997808] proxy/vless/outbound: tunneling request to tcp:104.26.13.205:443 via 80.253.255.10:443
2024/06/30 15:34:34 [Info] [510997808] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
```

I want to thank you sincerely. This tool has enabled us to complete several projects successfully.

**Comment by Mester-Dariush** [comment]
I apologize for completing and reopening, unfortunately I clicked on it by mistake 😁😅

**Comment by Mester-Dariush** [comment]
> Hello,
> 
> I am encountering an SSL/TLS certificate issue when using the proxy method. Below are the details of the commands I am using and the error I receive.
> 
> **Commands:** To create the proxy:
> 
> `xray-knife proxy -v -p 2342 -c vless://..........`
> 
> To test the proxy:
> 
> `curl --proxy socks5://localhost:2342 https://api.ipify.org?format=json`
> 
> Error: `curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed`
> 
> Terminal Output:
> 
> ```
> ==========INBOUND==========
> Protocol: Socks
> Remark: Listener
> Network: tcp
> Address: 127.0.0.1
> Port: 2342
> ============================
> 
> ==========OUTBOUND==========
> Protocol: Vless
> Remark:
> Network: tcp
> Address: 80.253.255.10
> Port: 443
> UUID: 7c7af2de-bb97-429f-ac3c-8ef849717491
> Flow: none
> TLS: none
> ============================
> 2024/06/30 15:34:15 [Debug] app/log: Logger started
> 2024/06/30 15:34:15 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:2342
> 2024/06/30 15:34:15 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:2342
> 2024/06/30 15:34:15 [Info] transport/internet/udp: listening UDP on 127.0.0.1:2342
> 2024/06/30 15:34:15 [Warning] core: Xray 1.8.13 started
> [+] 15:34:15 Started listening for new connections...
> 2024/06/30 15:34:29 [Info] [510997808] proxy/socks: TCP Connect request to tcp:104.26.13.205:443
> 2024/06/30 15:34:29 tcp:127.0.0.1:64690 accepted tcp:104.26.13.205:443 [socks >> proxy]
> 2024/06/30 15:34:34 [Info] [510997808] app/dispatcher: default route for tcp:104.26.13.205:443
> 2024/06/30 15:34:34 [Info] [510997808] transport/internet/tcp: dialing TCP to tcp:80.253.255.10:443
> 2024/06/30 15:34:34 [Debug] transport/internet: dialing to tcp:80.253.255.10:443
> 2024/06/30 15:34:34 [Info] [510997808] proxy/vless/outbound: tunneling request to tcp:104.26.13.205:443 via 80.253.255.10:443
> 2024/06/30 15:34:34 [Info] [510997808] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
> ```
> 
> I want to thank you sincerely. This tool has enabled us to complete several projects successfully.
I apologize for completing and reopening, unfortunately I clicked on it by mistake 😁😅

**Comment by Mester-Dariush** [comment]
I apologize for completing and reopening, unfortunately I clicked on it by mistake 😁😅

**Comment by Mester-Dariush** [comment]
Update: I realized that the problem is with the settings and some parameters of the json xray core config file and I was able to almost solve the problem.

You can find out by checking the config of programs like V2rayN.

Example:

```{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 23452,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "185.146.173.58",
            "port": 2052,
            "users": [
              {
                "id": "Telegram-ipV2Ray-weq",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/Telegram-ipV2Ray?ed=2048",
          "headers": {
            "Host": "Ch.1.V2rayV2ray-_-_-V2ray.Zemestanil.Ir."
          }
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "dns": {
    "hosts": {
      "dns.google": "8.8.8.8",
      "proxy.example.com": "127.0.0.1"
    },
    "servers": [
      {
        "address": "223.5.5.5",
        "domains": [
          "geosite:cn",
          "geosite:geolocation-cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ]
      },
      "1.1.1.1",
      "8.8.8.8",
      "https://dns.google/dns-query"
    ]
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "domain:example-example.com",
          "domain:example-example2.com"
        ]
      },
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn",
          "geosite:geolocation-cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ]
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy"
      }
    ]
  }
}```

Since I don't know enough about it, I can't say exactly which parameter solves this problem, but this configuration I tested did not have the SSL problem.

Thanks

**Comment by lilendian0x00** [comment]
Hey, thanks for reaching out. I'll check it as soon as I have free time
