### ISSUE TITLE
Batch Processing Stops Due to Bad Configuration

### ISSUE THREAD

**Issue by just1random** [lilendian0x00/xray-knife#11]
Hi again!

I hope you're doing well. I'm encountering a small problem with xray-knife. When proceeding with batch processing from a file, xray-knife crashes or stops upon receiving a bad configuration, and it does not check the rest of the configurations. It would be really helpful if the tool could ignore the bad configuration and continue processing the other configurations.

I'm using `net http --type csv --file "configurations.txt"`

Thank you for looking into this!

**Comment by lilendian0x00** [comment]
Hey, could you please send me the `configurations.txt` file?

xray-knife already ignores malformed configs, it might be a special case

**Comment by just1random** [comment]
Hey, I made a mistake. I didn't realize that I wasn't using the latest version of your project. Upon using the latest version, everything worked fine. The CLI throws an error but continues to work.
