### ISSUE TITLE
Reading config from STDIN even with the --file option

### ISSUE THREAD

**Issue by anshibanov** [lilendian0x00/xray-knife#12]
I am running xray-knife with the following command:

`./xray-knife proxy --file vless.link
`

In the vless.link file, I have a link in the format vless://..., which was generated by the x-ui panel.

After starting xray-knife, it still asks for the config from STDIN, even though I expect it to read the configuration from the link in vless.link.

![image](https://github.com/user-attachments/assets/a9fa1a03-0255-4290-a1f2-656065c5a0ef)

P.S. Anyway thx you for this tool! 🙏

**Comment by lilendian0x00** [comment]
Hey, 

You are running the the command with `--file` flag which is for passing a file of configs not for a single config.

You have to use `--config` or simply `-c` to pass a single config by argument.

Hope you enjoy it mate 😊
