### ISSUE TITLE
Problem with batch speed test

### ISSUE THREAD

**Issue by The-Erf** [lilendian0x00/xray-knife#14]
Hello, when I use the following command:

`./xray-knife net http -p --file /home/erfan/Desktop/TXT.txt -o cvs`
or
`./xray-knife net http --speedtest --file /home/erfan/Desktop/TXT.txt -o cvs`
or
`./xray-knife net http --speedtest speed.cloudflare.com --file /home/erfan/Desktop/TXT.txt -o cvs`

A cvs file is saved for me, but there is no speed test information (download and upload speed) in the file

**Comment by elegance666** [comment]
منم همین مشکل دارم خروجی فقط خود کانفیگ میده نه تست سرعت

**Comment by lilendian0x00** [comment]
به زودی مشکل حل می شود

**Comment by lilendian0x00** [comment]
As I tested the problem in the new version, it has been successfully solved, so I am closing this issue
