### ISSUE TITLE
فایل sample

### ISSUE THREAD

**Issue by elegance666** [lilendian0x00/xray-knife#16]
درود،
کاش راهنمایی میکردین چطوری میشه خروجی گرفت از تست سرورها مثل همون تصویری که تو راهنما هستش

و فایل STDIN باید به چه نامی باشه که خودکار بخونه؟

**Comment by elegance666** [comment]
config.yaml
باید باشه ولی فرمتش باید چطوری باشه تا بخونه؟

**Comment by elegance666** [comment]
من نیاز دارم تا خودکار چندتا سرور چک بشند و یک فایل تولید بشه تا از روی اون هر سروی لازم بود ری‌استارت کنم

**Comment by lilendian0x00** [comment]
سلام، STDIN فایل نیست و به معنای گرفتن مستقیم یک کانفیگ از standard input هست که همان ورودی کیبورد می شود
