### ISSUE TITLE
Nice Tool, some suggestions

### ISSUE THREAD

**Issue by AliM1988** [lilendian0x00/xray-knife#3]
It is very nice tool to test v2ray/xray configs. I hasn't seen any similar tool. (only vmessping, that doesn't work for me)

If it is possible separate tool from xray-core, then users can use other compatible version of xray-core.

Thank you for sharing.

**Comment by lilendian0x00** [comment]
Hello and thanks for your nice comment 🙏 It definitely made me happy. Appreciate it ❤️

There wasn't any satisfying software that could check xray config links in a bunch like this, so I decided to start making it and publish it so others can make use of it too. 

You can use other versions of `xray-core` by changing its value from `go.mod` file (You have to compile it after that by running `go build .` command).
