### ISSUE TITLE
$go build . go: errors parsing go.mod: /media/user/Local Disk/user/Programming/projects/0_people/xray-knife/go.mod:5: unknown directive: toolchain

### ISSUE THREAD

**Issue by m0x61h0x64i** [lilendian0x00/xray-knife#8]
$go build .
go: errors parsing go.mod:
/media/user/Local Disk/user/Programming/projects/0_people/xray-knife/go.mod:5: unknown directive: toolchain

**Comment by lilendian0x00** [comment]
Hey

Your Go version is old; it needs to be at least 1.21
